export * as alt from './Alt'
export * as applicative from './Applicative'
export * as apply from './Apply'
export * as compose from './Compose'
export * as contravariant from './Contravariant'
export * as equal from './Equal'
export * as failable from './Failable'
export * as foldable from './Foldable'
export * as functor from './Functor'
export * as fns from './functions'
export * from './HKT'
export * from './types'
export * as id from './Id'
export * as monad from './Monad'
export * as monoid from './Monoid'
export * as orderable from './Orderable'
export * as record from './Record'
export * as semigroup from './Semigroup'
export * as traversable from './Traversable'
